easy_vote/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^$', 'polls.views.index', name='index'),
)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.LastQuestionView.as_view(), name='last_question_view'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
    url(r'^poll/?$', views.create_poll, name='create_poll'),
    url(r'^(?P<question_id>\d+)/choices/$', views.create_choices,
        name='create_choices'),
)

polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from polls.models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        pass


class LastQuestionView(generic.ListView):
    template_name = 'polls/question_list.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))


def index(request):
    return render(request, 'polls/index.html')


def create_poll(request):
    if not request.POST:
        raise Http404
    else:
        if request.POST['question_text']:
            q = Question(question_text=request.POST['question_text'],
                         pub_date=timezone.now())
            q.save()
            return HttpResponseRedirect(reverse('polls:create_choices',
                                                args=(q.id,)))
        else:
            return render(request, 'polls/index.html', {
                          'error_message': 'The question cannot be empty.', })


def create_choices(request, question_id):
    if not request.POST:
        q = get_object_or_404(Question, pk=question_id)
        return render(request, 'polls/create_question.html',
                      {'question': q})
    else:
        q = get_object_or_404(Question, pk=question_id)
        if request.POST['answer_text_1'] and request.POST['answer_text_2']:
            q.choice_set.create(choice_text=request.POST['answer_text_1'],
                                votes=0)
            q.choice_set.create(choice_text=request.POST['answer_text_2'],
                                votes=0)
            return HttpResponseRedirect(reverse('polls:detail', args=(q.id,)))

        else:
            return render(request, 'polls/create_question.html',
                          {'question': q,
                           'error_message': 'At least two possible answers '
                                            'are needed'})

polls/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Easy Vote</title>

    <!-- Bootstrap -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
            {% block content %}
            {% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
</html>

polls/templates/polls/create_question.html
{% extends 'base.html' %}

{% block content %}
</br>
                    </br>
                        {% if question %}
                        <h1>{{ question.question_text }}</h1>
                        {% if error_message %}
                        <div class="col-sm-6 col-sm-offset-3">
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert">
                                    <span aria-hidden="true">&times;</span>
                                    <span class="sr-only">Close</span>
                                </button>
                                {{ error_message }}
                            </div>
                        </div>
                        {% endif %}
                        <form class="form-horizontal" role="form" action="{% url 'polls:create_choices' question.id %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="col-sm-4 col-md-offset-4 input-group">
                    <input class="form-control" type="text" name="answer_text_1" id="answer_text_1" placeholder="Enter new answer" />
                    </div>
                    <div class="col-sm-4 col-md-offset-4 input-group">
                    <input class="form-control" type="text" name="answer_text_2" id="answer_text_2" placeholder="Enter new answer" />
                    <span class="input-group-btn">
        <button class="btn btn-default" type="button">+</button>
      </span>
                </div>
                                                       </div>
                <input class="btn btn-lg btn-default" type="submit" value="Add possible answers" />
            </form>

                        {% endif %}
                        
{% endblock %}

polls/templates/polls/detail.html
{% extends 'base.html' %}

{% block content %}
</br>
</br>
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form class= "form-horizontal" role="form" action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <div class="form-group">
    {% for choice in question.choice_set.all %}
    <div class="col-sm-4 col-md-offset-4">
        <label>
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
            {{ choice.choice_text }}
        </label>
    </div>
    {% endfor %}
    </div>
    <input class="btn btn-lg btn-default" type="submit" value="Vote" />
</form>

{% endblock %}

polls/templates/polls/index.html
{% extends 'base.html' %}

{% block content %}
<div class="site-wrapper">
    <div class="site-wrapper-inner">
        <div class="cover-container">
            <h1 class="cover-heading">Ask your question</h1>
            </br>
            </br>
            {% if error_message %}
            <div class="col-sm-6 col-sm-offset-3">
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                        <span class="sr-only">Close</span>
                    </button>
                    {{ error_message }}
                </div>
            </div>
            {% endif %}
            <form class="form-horizontal" role="form" action="{% url 'polls:create_poll' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="col-sm-8 col-sm-offset-2">
                        <input class="form-control" type="text" name="question_text" id="question_text" placeholder="Enter new question" />
                    </div>
                </div>
                <input class="btn btn-lg btn-default" type="submit" value="Create Question" />
            </form>
            <div class="footer">
                <a href=" {% url 'polls:last_question_view' %} ">List of questions</a
            </div>
        </div>
    </div>
</div>

{% endblock %}

polls/templates/polls/question_list.html
{% extends 'base.html' %}

{% block content %}

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>